version: "1.0"

services:

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: '${GITLAB_HOSTNAME}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['${GITLAB_LETSENCRYPT_EMAIL}']
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        gitlab_rails['time_zone'] = '${GITLAB_TIMEZONE}'
    ports:
      - '${GITLAB_HTTP_PORT}:80'
      - '${GITLAB_HTTPS_PORT}:443'
      - '${GITLAB_SSH_MAP_PORT}:22'
      - '${GITLAB_REGISTRY_PORT}:5050'
    volumes:
      - '${GITLAB_CONFIG_PATH}:/etc/gitlab'
      - '${GITLAB_LOGS_PATH}:/var/log/gitlab'
      - '${GITLAB_DATA_PATH}:/var/opt/gitlab'
